version: 2
jobs:
  build:
    working_directory: ~/ah-rambo-frontend
    environment:
      CC_TEST_REPORTER_ID: 36d0eedfccae6543074d8efd8324aa9b2f17f879cc5fa132d6119e12070d7621
      COVERALLS_REPO_TOKEN: gAvwj1Kg64wkSpIgW8cnIxm65PiPWzJ1t

    docker:
      - image: circleci/node:10

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-{{ .Branch }}-

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          key: v1-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run:
          name: Run Tests
          command: npm test -- --runInBand --ci
      - store_artifacts:
          path: coverage


      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - run:
          name: Send Test Report to Code Climate
          command: |
            ./cc-test-reporter before-build
            ./cc-test-reporter after-build
            npm run coverage

